name: CI/CD 

on: 
  push:
  pull_request:

env:
  PROJECT_NAME: odh-gtfs-api
  DOCKER_IMAGE: ghcr.io/${{ github.repository }}/${{ github.event.repository.name }}
  DOCKER_TAG: ${{ github.sha }}

jobs:
  deploy-test:
    runs-on: ubuntu-22.04
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout source code
        uses: noi-techpark/github-actions/checkout@v2

      - name: REUSE Compliance Check
        uses: fsfe/reuse-action@v1

      - name: Create .env file
        uses: noi-techpark/github-actions/env-file@v2
        env:
          X_COMPOSE_PROJECT_NAME: ${{ env.PROJECT_NAME }}
          X_DOCKER_IMAGE: ${{ env.DOCKER_IMAGE }}
          X_DOCKER_TAG: ${{ env.DOCKER_TAG }}

          X_SERVER_PORT: 1091
          X_API_BASE_URL: https://gtfs.api.opendatahub.testingmachine.eu
          X_LOG_LEVEL: info

      - name: Build and push 
        uses: noi-techpark/github-actions/docker-build-and-push@v2
        with:
          docker-username: ${{ github.actor }}
          docker-password: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy application
        uses: noi-techpark/github-actions/docker-deploy@v2
        with:
          hosts: 'test'
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          docker-username: 'noi-techpark-bot'
          docker-password: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          project-name: ${{ env.PROJECT_NAME }}

#  deploy-prod:
#    runs-on: ubuntu-20.04
#    if: github.ref == 'refs/heads/prod'
#    # needs: test
#    steps:
#      - name: Checkout source code
#        uses: noi-techpark/github-actions/checkout@v2
#
#      - name: REUSE Compliance Check
#        uses: fsfe/reuse-action@v1
#
#      - name: Create .env file
#        uses: noi-techpark/github-actions/env-file@v2
#        env:
#         X_COMPOSE_PROJECT_NAME: ${{ env.PROJECT_NAME }}
#         X_DOCKER_IMAGE: ${{ env.DOCKER_IMAGE }}
#         X_DOCKER_TAG: ${{ env.DOCKER_TAG }}
#
#         X_PYTHONPATH: src
#         X_FLASK_ENV: production
#         X_FLASK_DEBUG: False
#         X_FLASK_SECRET_KEY: ${{ secrets.FLASK_SECRET_PROD }}
#         X_FLASK_SQLALCHEMY_TRACK_MODIFICATIONS: False
#         X_FLASK_SQLALCHEMY_DATABASE_URI: ${{ secrets.DB_URI_PROD }}
#
#         X_SERVER_PORT: 1014
#
#      - name: Build and push 
#        uses: noi-techpark/github-actions/docker-build-and-push@v2
#        with:
#          docker-username: ${{ github.actor }}
#          docker-password: ${{ secrets.GITHUB_TOKEN }}
#
#      - name: Deploy application
#        uses: noi-techpark/github-actions/docker-deploy@v2
#        with:
#          hosts: 'prod'
#          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
#          docker-username: 'noi-techpark-bot'
#          docker-password: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
#          project-name: ${{ env.PROJECT_NAME }}